# Generated by Django 4.1.7 on 2023-02-28 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('proffession', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
