# Generated by Django 4.1.7 on 2023-02-28 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testimonial', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Team',
            new_name='Testimonial',
        ),
    ]
