# Generated by Django 4.1.7 on 2023-02-21 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0002_subscribers_country_subscribers_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribers',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
