# Generated by Django 4.1.7 on 2023-02-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0004_delete_mailmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(null=True)),
            ],
        ),
    ]
