# Generated by Django 4.1.7 on 2023-02-21 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('letter', '0005_mailmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailmessage',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
