# Generated by Django 4.1.7 on 2023-02-27 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customermessage',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
