# Generated by Django 4.1.7 on 2023-02-28 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=100, null=True)),
                ('link', models.TextField(null=True)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
