# Generated by Django 4.2 on 2023-04-07 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='link',
            field=models.TextField(blank=True, null=True),
        ),
    ]
