# Generated by Django 4.1.7 on 2023-02-17 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buniwacreations', '0002_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
