# Generated by Django 4.1.7 on 2023-02-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buniwacreations', '0003_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
    ]
