# Generated by Django 4.1.7 on 2023-02-28 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buniwacreations', '0005_facts_delete_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='facts',
        ),
    ]
