# Generated by Django 4.1.7 on 2023-02-28 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buniwacreations', '0007_customermessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomerMessage',
            new_name='CustomerMessageQuote',
        ),
    ]
