# Generated by Django 4.2 on 2023-04-06 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buniwacreations', '0008_rename_customermessage_customermessagequote'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTestimonial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('proffession', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('image', models.ImageField(upload_to='pics')),
            ],
        ),
    ]
