# Generated by Django 4.2 on 2023-04-06 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buniwacreations', '0009_hometestimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomeTestimonial',
        ),
    ]
