# Generated by Django 4.2 on 2023-04-06 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buniwacreations', '0010_delete_hometestimonial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Team',
        ),
    ]
